### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by slobentanzer** [saezlab/BioCypher#13]

**Comment by deeenes** [comment]
Here the first question is whether we use the Python `logging` module or the one from pypath (https://github.com/saezlab/pypath/blob/master/src/pypath/share/log.py). I like the pypath one, and it has the advantage that all log messages will go into the same file.

**Comment by slobentanzer** [comment]
I started with the Python logging (wanted to learn it), and I had no troubles sending it to one file; maybe it has gotten better since you last looked at it. You can check it out on the latest commit.
