### ISSUE TITLE
wrong documentation version online

### ISSUE THREAD

**Issue by vincentvialard** [saezlab/BioCypher#139]
the documentation of the 'modularize' branch (v0.5.2) was pushed online instead of the one from from the 'main' branch (v0.4.5).
it is very confusing as there are breaking changes in the configuration...

**Comment by slobentanzer** [comment]
shoot, that should not have happened; will try to fix asap

**Comment by slobentanzer** [comment]
should be reverted now. i need to find out how to turn this off for the branches that are not `main`
