### ISSUE TITLE
Sphinx build (GitHub Action): no module named 'build'

### ISSUE THREAD

**Issue by slobentanzer** [saezlab/BioCypher#19]
Sphinx build fails on remote for unknown reason since [5bb4188](https://github.com/saezlab/BioCypher/commit/5bb41887a41f3c89512640cedc4ea1b8c4ced3b2). The Warning in the GitHub action execution (Build docs step [here](https://github.com/saezlab/BioCypher/runs/4693044086?check_suite_focus=true)) states "no module named 'build'"; however, I am not trying to add a module with that name, and the warning applies to every module it tries to add (and thus, documentation for all modules on the remote is empty).

The really weird thing is that this commit does not change anything even remotely related to Sphinx, I have no idea where the problem lies. The commit changes formatting in the batch writer and refactors the corresponding test, none of which should affect Sphinx.

I also tried re-running the older actions to check whether a Sphinx update broke something, but the older builds still re-run without problems. In addition, the local Sphinx build (VSCode preview function) still works as well.

**Comment by deeenes** [comment]
See here :)

https://github.com/saezlab/BioCypher/blob/b7fab59869f5d054813eb28ed15a5cd475b9df07/biocypher/driver.py#L30

**Comment by slobentanzer** [comment]
Cool, thanks!

I guess if I push multiple commits at once, only the latest one gets built by the action, right? So this is why there was no change in that specific commit.

**Comment by deeenes** [comment]
> 
> I guess if I push multiple commits at once, only the latest one gets built by the action, right?

Yes
