### ISSUE TITLE
Node identifiers containing `:`

### ISSUE THREAD

**Issue by slobentanzer** [saezlab/BioCypher#25]
@deeenes you have introduced a string replacement for the complex IDs from pypath, changing `COMPLEX:` to `COMPLEX_`. Was there a problem with Neo4j that prompted this?

The reason I ask is because I noticed you didn't catch all colons in identifiers; we still have a couple `COMPLEX_CHEBI:etc` nodes in the graph. At least with the admin import, there does not seem to be a problem with `:`. Why did you do the replacement initially?

**Comment by deeenes** [comment]
Have I changed the colon? Maybe only in my first Neo4j example? If it's not a problem, then we can just leave it like that. One thing is the colon we use for labelling the complexes (`COMPLEX:A_B_C_D`) and another thing that certain databases include a prefix in their identifiers (`CHEBI:0001`). In the latter case it's not us who adds the colon. We haven't really used any such identifier so far, it's a question whether it causes issues in pypath or Neo4j.
