### ISSUE TITLE
Broken link in the landing page

### ISSUE THREAD

**Issue by ahmetrifaioglu** [saezlab/BioCypher#30]
There is a broken link named as **PyPath adapter** at [BioCypher Landing page](https://saezlab.github.io/BioCypher/#the-host-module-adapter) under the host Module Adapter title. I think it should be corrected as [this](https://github.com/saezlab/pypath/blob/master/pypath/biocypher/adapter.py).

**Comment by slobentanzer** [comment]
good catch, didn't realise denes had already merged the major refactor of directory structure to pypath.
