### ISSUE TITLE
Infinite loop if class name matches `is_a` value

### ISSUE THREAD

**Issue by pedrohr** [saezlab/BioCypher#92]
If a class name matches the value of `is_a` schema value, the adapter enters an infinite loop.

Example:

_schema-config.yml_

```
variant to gene association:
  is_a: variant to gene association
  represented_as: edge
  source: sequence variant
  target: sequence variant

```
Suggested fix: add a check for `is_a` values and fail if it matches the class name.

**Comment by slobentanzer** [comment]
Hi @pedrohr,
thanks for the report, and good solution. We are currently refactoring the entire package, so we can take care of that in the process. @deeenes, could you add that?
