### ISSUE TITLE
Default delimiter caues  IllegalArgumentException: Unsupported character '??'

### ISSUE THREAD

**Issue by AndiMajore** [saezlab/BioCypher#94]
Not specifying a delimiter and thus using the default (broken pipe: ¦ ) causes following error on admin import execution under neo4j 4.4 (Ubuntu 22.04.1, Java 11):
`Invalid value for option '--delimiter': cannot convert '??' to char (java.lang.IllegalArgumentException: Unsupported character '??')`

**Comment by slobentanzer** [comment]
Weirdly, I have not been able to replicate this error consistently. I have seen it once, probably by accident, but with the tab character, which is even weirder. I am starting to think this is something not related to Java.

Does the same happen with other separator characters, @AndiMajore?

**Comment by slobentanzer** [comment]
@AndiMajore I still have not encountered this again; granted, I haven't been doing much novel importing into Neo4j. Were you able to figure out more about this issue, did it happen again?

**Comment by slobentanzer** [comment]
I figured it out: it seems to happen when using double quotes in the YAML configuration. This allows escape characters to go through the internal Python representation of the string and on to the output. In combination with the `.encode('unicode_escape').decode('utf-8')` that we were doing to prevent weird characters in the shell script file, some characters were badly converted. Switched to recommending single quotes for all config files in the docs as well as a check for questionable characters in double quotes at the read-in of the YAML files; addressed in [198876c](https://github.com/saezlab/BioCypher/commit/198876c15af431f19e0cd6a459a8ec8549ec4d79).
